/*
 * CreativeConnect — server-side rendering helpers.
 *  - renderHome(): injects DB content into the home page template
 *    (hero + trust strip + footer blurb) so above-the-fold text is correct
 *    on first paint. Packages & portfolio are rendered in the browser from
 *    the generated config below.
 *  - generateConfigJs(): builds the window.CC_CONFIG script from the DB.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { getPublicConfig } = require("./db");

const ROOT = path.join(__dirname, "..");
const HOME_TEMPLATE = path.join(ROOT, "index.html");

function escapeHtml(str) {
  return String(str == null ? "" : str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderHome(baseUrl) {
  const cfg = getPublicConfig();
  let html = fs.readFileSync(HOME_TEMPLATE, "utf8");

  const trustItems = (cfg.trust || [])
    .map((t) => "<li>" + escapeHtml(t) + "</li>")
    .join("\n          ");

  const replacements = {
    "{{HERO_EYEBROW}}": escapeHtml(cfg.hero.eyebrow),
    "{{HERO_TITLE}}": escapeHtml(cfg.hero.title),
    "{{HERO_SUBTITLE}}": escapeHtml(cfg.hero.subtitle),
    "{{TRUST_ITEMS}}": trustItems,
    "{{FOOTER_ABOUT}}": escapeHtml(cfg.footerAbout)
  };

  for (const [token, value] of Object.entries(replacements)) {
    html = html.split(token).join(value);
  }

  // Inject LocalBusiness structured data (JSON-LD) for SEO.
  html = html.replace("</head>", jsonLd(cfg, baseUrl) + "\n</head>");
  return html;
}

// Schema.org ProfessionalService / LocalBusiness for rich results.
function jsonLd(cfg, baseUrl) {
  const wa = String(cfg.whatsapp || "").replace(/[^0-9]/g, "");
  const data = {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    name: cfg.businessName || "CreativeConnect",
    description: (cfg.hero && cfg.hero.subtitle) || "",
    areaServed: "Maldives",
    address: { "@type": "PostalAddress", addressLocality: "Malé", addressCountry: "MV" }
  };
  if (baseUrl) data.url = baseUrl + "/";
  if (cfg.email) data.email = cfg.email;
  if (wa) data.telephone = "+" + wa;
  const sameAs = [];
  if (cfg.instagramHandle) sameAs.push("https://instagram.com/" + cfg.instagramHandle);
  if (sameAs.length) data.sameAs = sameAs;
  return '<script type="application/ld+json">' + JSON.stringify(data).replace(/</g, "\\u003c") + "</script>";
}

// Serialize the public config as an assignable script. `<` is escaped so a
// value can never break out of the <script> tag.
function generateConfigJs() {
  const cfg = getPublicConfig();
  const json = JSON.stringify(cfg).replace(/</g, "\\u003c");
  return (
    "/* Generated by the CreativeConnect server from the database. */\n" +
    "window.CC_CONFIG = " +
    json +
    ";\n"
  );
}

module.exports = { renderHome, generateConfigJs, escapeHtml };
